version: "3.8"
services:
  backend:
    image: ricex407/s3-image-uploader:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      DATABASE_URL: "mongodb+srv://tech:${MONGO_PASSWORD}@imagecluster.hzp6rqt.mongodb.net/?retryWrites=true&w=majority&appName=ImageCluster"

  frontend:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
