name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Pull the latest images
        run: docker-compose pull

      - name: Shutdown old containers
        run: docker-compose down

      - name: Rebuild the backend container
        run: docker-compose build s3-image-uploader-container

      - name: Deploy with Docker Compose
        run: docker-compose up -d
