name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest Docker image
        run: sudo docker pull ricex407/rice-personal-site:latest

      - name: Stop the current container
        run: docker stop rice-personal-site-container || true

      - name: Remove the stopped container
        run: docker rm rice-personal-site-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            --net rice-personal-site-network \
            -p 80:80 \
            --name rice-personal-site-container \
            ricex407/rice-personal-site:latest
