name: CD for rice-personal-site

on:
  workflow_run:
    workflows: ["CI for rice-personal-site"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest Docker images
        run: sudo docker pull ricex407/rice-personal-site:latest

      - name: Delete old container
        run: docker rm -f rice-personal-site-container

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name rice-personal-site-container ricex407/rice-personal-site
