name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Pull the latest images
        run: docker-compose pull

      - name: Shutdown old containers
        run: docker-compose down

      - name: Remove existing s3-image-uploader-container
        run: |
          if docker container ls -a | grep -q s3-image-uploader-container; then
            docker container rm -f s3-image-uploader-container
          fi

      - name: Deploy with Docker Compose
        run: docker-compose up -d
        env:
          API_PORT: ${{ secrets.API_PORT }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}

      - name: Clean up any unused Docker resources
        run: docker system prune -af
