name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Pull the latest images
        run: docker-compose pull

      - name: Shutdown old containers
        run: docker-compose down

      - name: Remove existing rice-personal-api-container
        run: |
          if docker container ls -a | grep -q rice-personal-api-container; then
            docker container rm -f rice-personal-api-container
          fi

      - name: Deploy with Docker Compose
        run: docker-compose up -d
        env:
          API_PORT: ${{ secrets.API_PORT }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BACKEND_BUCKET_NAME: ${{ secrets.AWS_BACKEND_BUCKET_NAME }}
          AWS_SES_SENDER: ${{ secrets.AWS_SES_SENDER }}
          PERSONAL_EMAIL: ${{ secrets.PERSONAL_EMAIL }}
          MONGO_DB_LOCAL_URI: ${{ secrets.MONGO_DB_LOCAL_URI }}

      - name: Check Docker containers status
        run: docker ps -a

      - name: Capture Docker logs
        run: docker-compose logs

      - name: Clean up any unused Docker resources
        run: docker system prune -af
