name: CD for rice-personal-site

on:
  workflow_run:
    workflows: ["CI for rice-personal-site"]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest Docker image
        run: sudo docker pull ricex407/rice-personal-site:latest

      - name: Stop the current container
        run: sudo docker stop rice-personal-site-container || true

      - name: Remove the stopped container
        run: sudo docker rm rice-personal-site-container || true

      - name: Run the new container
        run: |
          docker run -d --name rice-personal-site-container -p 3000:80 \
          -e VITE_GOOGLE_ANALYTICS_TAG=${{ secrets.VITE_GOOGLE_ANALYTICS_TAG }} \
          -e VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }} \
          ricex407/rice-personal-site:latest
